# Generated by Django 4.1.7 on 2023-03-05 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_etiqueta_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etiqueta',
            name='produto',
        ),
        migrations.AddField(
            model_name='produto',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.etiqueta'),
        ),
    ]
