# Generated by Django 4.1.7 on 2023-03-30 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_produto_produto_etiqueta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
    ]
