# Generated by Django 4.1.7 on 2023-03-30 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_produto_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='cerveja',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='coca',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='hamburguer',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cerveja',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='coca',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='hamburguer',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.AddField(
            model_name='estoque',
            name='produto',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estoque',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='produto',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='core.produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='quantidade',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
