# Generated by Django 4.1.7 on 2023-03-30 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_estoque_produto_remove_estoque_quantidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
    ]
